name: "Macromolecular Conformational Ensemble Conference"
description: ""

url: "http://conformational_ensembles.github.io"

gems: [jekyll-paginate]
paginate: 10
paginate_path: "blog/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown: 
  parse_block_html: true
